# This is a basic workflow to help you get started with Actions

name: Gettings apps

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  get:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Maximize disk space
      uses: easimon/maximize-build-space@master
      with:
          root-reserve-mb: 5120
          remove-dotnet: true
          remove-android: true
          remove-docker-images: true

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Install dependencies
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
       sudo apt update
       sudo apt install -y git wget curl bash coreutils util-linux ccache dos2unix sudo jq moreutils inetutils-ping netcat-openbsd --no-install-suggests

    - name: Settings DoT DNS with systemd-resolved
      run: |
       sudo mkdir -p /etc/systemd/resolved.conf.d/
       echo -e "[Resolve]\nDNS=8.8.4.4#dns.google\nFallbackDNS=\nDNSOverTLS=yes\nDNSSEC=yes\nCache=no\nCacheFromLocalhost=no\nReadEtcHosts=no" | sudo tee /etc/systemd/resolved.conf.d/google.conf &>/dev/null;
       echo -e "[Resolve]\nDNS=1.0.0.1#1dot1dot1dot1.cloudflare-dns.com\nFallbackDNS=\nDNSOverTLS=yes\nDNSSEC=yes\nCache=no\nCacheFromLocalhost=no\nReadEtcHosts=no" | sudo tee /etc/systemd/resolved.conf.d/cloudflare.conf &>/dev/null;
       cat /etc/systemd/resolved.conf.d/google.conf
       echo ""
       cat /etc/systemd/resolved.conf.d/cloudflare.conf
       echo ""
       echo "nameserver 127.0.0.53" | sudo tee /etc/resolv.conf.DNSoverride &>/dev/null;
       sudo ln -svf /etc/resolv.conf.DNSoverride /etc/resolv.conf
       cat -n /etc/resolv.conf
       echo ""
       cat -n /etc/hosts
       echo ""
       sudo systemctl restart systemd-resolved.service && sleep 3s

    - name: Test DNS-query
      run: |
       set -e
       nslookup -type=A google.com
       echo ""
       dig google.com A

    - name: Test DNS my HOME domain and check port proxy (available host)
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
      run: |
       set -e
       nslookup -type=A ${HOME_DOMAIN} &>/dev/null
       echo ""
       dig ${HOME_DOMAIN} A +short &>/dev/null
       nc -z -v ${HOME_DOMAIN} 8365 &>/dev/null

    - name: Gettings certificate and SSH-key from private repository
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY }}
        NAME_ACCOUNT_GITHUB: you-oops-dev
      run: |
       curl -4 -H "Authorization: token ${TOKEN}" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0' --max-time 300 --retry-delay 3 --retry 10 -# https://raw.githubusercontent.com/${NAME_ACCOUNT_GITHUB}/${REPOSITORY}/main/squidCA_import_client.crt > ./squidCA_import_client.crt
       curl -4 -H "Authorization: token ${TOKEN}" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0' --max-time 300 --retry-delay 3 --retry 10 -# https://raw.githubusercontent.com/${NAME_ACCOUNT_GITHUB}/${REPOSITORY}/main/id_rsa > ./id_rsa
       curl -4 -H "Authorization: token ${TOKEN}" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0' --max-time 300 --retry-delay 3 --retry 10 -# https://raw.githubusercontent.com/${NAME_ACCOUNT_GITHUB}/${REPOSITORY}/main/id_rsa.pub > ./id_rsa.pub
       sudo mkdir -pv ${HOME}/.ssh/ && sudo mv id_rsa* ${HOME}/.ssh/ && sudo chown -Rc runner:runner ${HOME}/.ssh/ && sudo chmod -c 700 ${HOME}/.ssh/ && sudo chmod -c 600 ${HOME}/.ssh/id_rsa && sudo chmod -c 600 ${HOME}/.ssh/id_rsa.pub && sudo cp -pvf ${HOME}/.ssh/id_rsa* ./

    - name: Install certificate in system
      env:
        NAME_ACCOUNT_GITHUB: you-oops-dev
      run: |
       sudo mkdir -pv /usr/local/share/ca-certificates
       sudo mv -f ./squidCA_import_client.crt /usr/local/share/ca-certificates/${NAME_ACCOUNT_GITHUB}.crt && sudo chown -c root:root /usr/local/share/ca-certificates/${NAME_ACCOUNT_GITHUB}.crt
       sudo update-ca-certificates --fresh -v

#    - name: Getting Yota
#      env:
#        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
#        SUPER_SECRET1: ${{ secrets.PASS }}
#        SUPER_SECRET2: ${{ secrets.USERNAME }}
#        USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 YaBrowser/26.6.0.0 Safari/537.36
#        DIRECT_LINK: https://static.yota.ru/upload/apps/ru.yota.android.apk 
#      run: |
#       curl -4 -H 'User-Agent: ${USER_AGENT}' -# --max-time 300 --retry-delay 3 --retry 10 -x https://${SUPER_SECRET2}:${SUPER_SECRET1}@${HOME_DOMAIN}:8365 -O ${DIRECT_LINK} > /dev/null

#    - name: Getting Avito
#      env:
#        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
#        SUPER_SECRET1: ${{ secrets.PASS }}
#        SUPER_SECRET2: ${{ secrets.USERNAME }}
#        USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 YaBrowser/26.6.0.0 Safari/537.36
#        DIRECT_LINK: https://www.avito.st/s/app/apk/avito.apk 
#      run: |
#       curl -4 -H 'User-Agent: ${USER_AGENT}' -# --max-time 300 --retry-delay 3 --retry 10 -x https://${SUPER_SECRET2}:${SUPER_SECRET1}@${HOME_DOMAIN}:8365 -O ${DIRECT_LINK} > /dev/null

#    - name: Getting Sber Online
#      env:
#        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
#        SUPER_SECRET1: ${{ secrets.PASS }}
#        SUPER_SECRET2: ${{ secrets.USERNAME }}
#        USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 YaBrowser/26.6.0.0 Safari/537.36
#        DIRECT_LINK: https://cdnweb.sberbank.ru/appdistr/SberbankOnline.apk
#      run: |
#       curl -4 -H 'User-Agent: ${USER_AGENT}' -# --max-time 300 --retry-delay 3 --retry 10 -x https://${SUPER_SECRET2}:${SUPER_SECRET1}@${HOME_DOMAIN}:8365 -O ${DIRECT_LINK} > /dev/null

#    - name: Getting T-bank
#      env:
#        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
#        SUPER_SECRET1: ${{ secrets.PASS }}
#        SUPER_SECRET2: ${{ secrets.USERNAME }}
#        USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 YaBrowser/26.6.0.0 Safari/537.36
#        DIRECT_LINK: https://acdn.t-bank-app.ru/download_apk/tbank_app.apk 
#      run: |
#       curl -4 -H 'User-Agent: ${USER_AGENT}' -# --max-time 300 --retry-delay 3 --retry 10 -x https://${SUPER_SECRET2}:${SUPER_SECRET1}@${HOME_DOMAIN}:8365 -O ${DIRECT_LINK} > /dev/null

#    - name: Getting BSPB
#      env:
#        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
#        SUPER_SECRET1: ${{ secrets.PASS }}
#        SUPER_SECRET2: ${{ secrets.USERNAME }}
#        USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 YaBrowser/26.6.0.0 Safari/537.36
#        DIRECT_LINK: https://www.bspb.ru/media/prod_app_bspb_b2c_android_c073c6d24f.apk 
#      run: |
#       curl -4 -H 'User-Agent: ${USER_AGENT}' -# --max-time 300 --retry-delay 3 --retry 10 -x https://${SUPER_SECRET2}:${SUPER_SECRET1}@${HOME_DOMAIN}:8365 -O ${DIRECT_LINK} > /dev/null

    - name: Getting Yota SSH variant
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
        USER_SSH: ${{ secrets.USERNAME_SSH }}
        APP_NAME: yota
      run: |
       scp -i ./id_rsa ${USER_SSH}@${HOME_DOMAIN}:/home/${USERNAME_SSH}/apps/*${APP_NAME}* ./

    - name: Getting Avito SSH variant
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
        USER_SSH: ${{ secrets.USERNAME_SSH }}
        APP_NAME: avito
      run: |
       scp -i ./id_rsa ${USER_SSH}@${HOME_DOMAIN}:/home/${USERNAME_SSH}/apps/*${APP_NAME}* ./

    - name: Getting BSPB SSH variant
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
        USER_SSH: ${{ secrets.USERNAME_SSH }}
        APP_NAME: bspb
      run: |
       scp -i ./id_rsa ${USER_SSH}@${HOME_DOMAIN}:/home/${USERNAME_SSH}/apps/*${APP_NAME}* ./

    - name: Getting Sberbank-Online SSH variant
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
        USER_SSH: ${{ secrets.USERNAME_SSH }}
        APP_NAME: sberbankonline
      run: |
       scp -i ./id_rsa ${USER_SSH}@${HOME_DOMAIN}:/home/${USERNAME_SSH}/apps/*${APP_NAME}* ./

    - name: Getting T-Bank SSH variant
      env:
        HOME_DOMAIN: ${{ secrets.DOMAIN_MY_HOME }}
        USER_SSH: ${{ secrets.USERNAME_SSH }}
        APP_NAME: tbank
      run: |
       scp -i ./id_rsa ${USER_SSH}@${HOME_DOMAIN}:/home/${USERNAME_SSH}/apps/*${APP_NAME}* ./
